import { describe, expect, test } from "bun:test";
import { parseLockfile } from "./lockfiles";

function versions(basename: string, content: string) {
  const parsed = parseLockfile({ basename, content });
  return parsed == null ? null : Object.fromEntries(parsed);
}

describe("parseLockfile", () => {
  test("package-lock.json v3 reads direct node_modules entries only", () => {
    const lock = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": { dependencies: { express: "^4.18.0" } },
        "node_modules/express": { version: "4.18.2" },
        "node_modules/@scope/pkg": { version: "1.2.3" },
        "node_modules/express/node_modules/debug": { version: "2.6.9" },
      },
    });
    expect(versions("package-lock.json", lock)).toEqual({
      express: "4.18.2",
      "@scope/pkg": "1.2.3",
    });
  });

  test("package-lock.json v1 reads the dependencies map", () => {
    const lock = JSON.stringify({
      lockfileVersion: 1,
      dependencies: { express: { version: "4.17.1" } },
    });
    expect(versions("package-lock.json", lock)).toEqual({ express: "4.17.1" });
  });

  test("pnpm-lock.yaml v9 importers with peer suffixes", () => {
    const lock = [
      "lockfileVersion: '9.0'",
      "importers:",
      "  .:",
      "    dependencies:",
      "      express:",
      "        specifier: ^4.18.0",
      "        version: 4.18.2",
      "      '@nestjs/core':",
      "        specifier: ^10.0.0",
      "        version: 10.3.0(reflect-metadata@0.1.13)",
      "packages:",
      "  express@4.18.2:",
      "    resolution: {integrity: sha512-x}",
    ].join("\n");
    expect(versions("pnpm-lock.yaml", lock)).toEqual({
      express: "4.18.2",
      "@nestjs/core": "10.3.0",
    });
  });

  test("pnpm-lock.yaml v5 inline versions", () => {
    const lock = [
      "lockfileVersion: 5.4",
      "dependencies:",
      "  express: 4.18.2",
      "  fastify: 4.26.0",
      "packages:",
      "  /express/4.18.2:",
      "    dev: false",
    ].join("\n");
    expect(versions("pnpm-lock.yaml", lock)).toEqual({
      express: "4.18.2",
      fastify: "4.26.0",
    });
  });

  test("yarn.lock v1 and berry", () => {
    const v1 = [
      "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
      "# yarn lockfile v1",
      "",
      '"@scope/pkg@^1.0.0", "@scope/pkg@^1.1.0":',
      '  version "1.2.3"',
      "",
      "express@^4.18.0:",
      '  version "4.18.2"',
    ].join("\n");
    expect(versions("yarn.lock", v1)).toEqual({
      "@scope/pkg": "1.2.3",
      express: "4.18.2",
    });
    const berry = [
      "__metadata:",
      "  version: 8",
      "",
      '"express@npm:^4.18.0":',
      "  version: 4.18.2",
      '  resolution: "express@npm:4.18.2"',
    ].join("\n");
    expect(versions("yarn.lock", berry)).toEqual({ express: "4.18.2" });
  });

  test("Gemfile.lock takes direct specs and strips platform suffixes", () => {
    const lock = [
      "GEM",
      "  remote: https://rubygems.org/",
      "  specs:",
      "    pg (1.5.4)",
      "    rails (7.1.3)",
      "      actionpack (= 7.1.3)",
      "    nokogiri (1.16.0-arm64-darwin)",
      "",
      "PLATFORMS",
      "  ruby",
    ].join("\n");
    expect(versions("Gemfile.lock", lock)).toEqual({
      pg: "1.5.4",
      rails: "7.1.3",
      nokogiri: "1.16.0",
    });
  });

  test("poetry.lock and uv.lock [[package]] tables", () => {
    const lock = [
      "[[package]]",
      'name = "fastapi"',
      'version = "0.116.0"',
      "",
      "[[package]]",
      'name = "SQLAlchemy"',
      'version = "2.0.30"',
    ].join("\n");
    expect(versions("poetry.lock", lock)).toEqual({
      fastapi: "0.116.0",
      sqlalchemy: "2.0.30",
    });
    expect(versions("uv.lock", lock)).toEqual({
      fastapi: "0.116.0",
      sqlalchemy: "2.0.30",
    });
  });

  test("Pipfile.lock strips == pins", () => {
    const lock = JSON.stringify({
      _meta: {},
      default: { requests: { version: "==2.32.0" } },
      develop: { pytest: { version: "==8.0.0" } },
    });
    expect(versions("Pipfile.lock", lock)).toEqual({
      requests: "2.32.0",
      pytest: "8.0.0",
    });
  });

  test("packages.lock.json reads direct resolved versions", () => {
    const lock = JSON.stringify({
      version: 1,
      dependencies: {
        "net9.0": {
          Npgsql: { type: "Direct", resolved: "9.0.1" },
          "System.Memory": { type: "Transitive", resolved: "4.5.5" },
        },
      },
    });
    expect(versions("packages.lock.json", lock)).toEqual({ npgsql: "9.0.1" });
  });

  test("composer.lock strips a leading v", () => {
    const lock = JSON.stringify({
      packages: [{ name: "laravel/framework", version: "v11.2.0" }],
      "packages-dev": [],
    });
    expect(versions("composer.lock", lock)).toEqual({
      "laravel/framework": "11.2.0",
    });
  });

  test("unrecognized content returns null", () => {
    expect(versions("package-lock.json", "not json")).toBeNull();
    expect(versions("yarn.lock", "garbage")).toBeNull();
    expect(versions("Gemfile.lock", "garbage")).toBeNull();
    expect(versions("unknown.lock", "")).toBeNull();
  });
});
